language: node_js
sudo: false
node_js:
  - "14"

  services:
    - docker

jobs:
  include:
  - name: "Deploy to staging"
    if: (type = push OR type = pull_request) AND branch = staging
    env:
    
    notifications:
