version: '3'
services:
  web:
    image: node:latest
    container_name: mingling-app
    build:
      context: .
      dockerfile: ./shared/config/Dockerfile.dev
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - 8000:9000
    environment:
      - CHOKIDAR_USEPOLLING=true

