jobs:
  test:
    executor:
      name: node/default
      tag: '14.15'
    steps:
      - checkout
      - node/install-packages
      - run:
          command: npx audit-ci -h -c
      - run:
          command: npm ci
      - run:
          command: npm run build

orbs:
  node: circleci/node@4.1.0
  aws-ecr: circleci/aws-ecr@6.2.0
  aws-ecs: circleci/aws-ecs@0.0.11
version: 2.1
workflows:
  run_tests:
    jobs:
      - test:
          filters:
            branches:
              only: staging
      - aws-ecr/build-and-push-image:
          dockerfile: Dockerfile
          repo: '${AWS_RESOURCE_NAME_PREFIX}'
          tag: "$CIRCLE_SHA1"
          requires:
            - test
          filters:
             branches:
                 only: staging
