jobs:
  test:
    executor:
      name: node/default
      tag: '14.15'
    steps:
      - checkout
      - node/install-packages
      - run:
          command: npx audit-ci -h -c
      - run:
          command: npm ci
      - run:
          command: npm run test:runner
  shellcheck:
orbs:
  node: circleci/node@4.1.0
  shellcheck: circleci/shellcheck@2.2.2
version: 2.1
workflows:
  test_my_app:
    jobs:
      - test:
          filters:
            branches:
              only: staging
      - shellcheck/check:
          dir: ./deploy.sh
          requires: - test

