jobs:
  test:
    executor:
      name: node/default
      tag: 14.15
    steps:
      - checkout
      - node/install-packages
      - run:
          command: npx audit-ci -h -c
      - run:
          command: npm ci --production
      - run:
          command: npm run build

orbs:
  node: circleci/node@4.1.0
  aws-ecr: circleci/aws-ecr@6.15.2
  aws-ecs: circleci/aws-ecs@0.0.11
version: 2.1
workflows:
  run_tests:
    jobs:
      - test:
          context: staging
          filters:
            branches:
              only: staging
      - aws-ecr/build-and-push-image:
          context: staging
          account-url: AWS_ECR_ACCOUNT_URL
          aws-access-key-id: AWS_ACCESS_KEY_ID
          aws-secret-access-key: AWS_SECRET_ACCESS_KEY
          dockerfile: Dockerfile
          no-output-timeout: 20m
          attach-workspace: true
          region: AWS_DEFAULT_REGION
          repo: $AWS_RESOURCE_NAME_PREFIX
          tag: 'latest'
          requires:
            - test
          filters:
             branches:
                 only: staging
