jobs:
  test:
    executor:
      name: node/default
      tag: '14.15'
    steps:
      - checkout
      - node/install-packages
      - run:
          command: npx audit-ci -h -c
      - run:
          command: npm ci
      - run:
          command: npm run build
      - run:
          command: echo $PWD
  pre-integration-checkout-workspace-job:
    executor:
      name: orb-tools/alpine
      resource-class: small
    steps:
      - checkout
      - persist_to_workspace:
          root: .
          paths: [Dockerfile]

job_template: &job_template
  account-url: AWS_ECR_ACCOUNT_URL
  aws-access-key-id: AWS_ACCESS_KEY_ID
  aws-secret-access-key: AWS_SECRET_ACCESS_KEY
  dockerfile: Dockerfile
  no-output-timeout: 20m
  workspace-root: '.'
  region: AWS_DEFAULT_REGION
  repo: $AWS_RESOURCE_NAME_PREFIX
  path: '.'
  skip-when-tags-exist: false
  attach-workspace: true
  tag: 'latest'
  requires:
    - test
  filters:
      branches:
          only: staging

orbs:
  orb-tools: circleci/orb-tools@9.0
  node: circleci/node@4.1.0
  aws-ecr: circleci/aws-ecr@6.15.2
version: 2.1
workflows:
  run_tests:
    jobs:
      - test:
          context: staging
          filters:
            branches:
              only: staging
      - pre-integration-checkout-workspace-job:
          name: pre-integration
          requires:
            - test
      - aws-ecr/build-and-push-image:
          context: staging
          <<: *job_template
