jobs:
  test:
    executor:
      name: node/default
      tag: '14.15'
    steps:
      - checkout
      - run:
          name: "Install packages"
          command: |
            npm ci
      - run:
          name: "Run all inspections"
          command: |
            npm run inspect:all:ci
      - run:
          name: "Check bundle size"
          command: |
            npm run build
      - run:
          name: "Run test coverage"
          command: |
              npm run test:coverage
      - store_artifacts:
          path: ./licenses
      - store_artifacts:
          path: ./bundleAnalyzer
      - store_artifacts:
          path: ./coverage
      - store_artifacts:
          path: ./AuditReport

aws_job_template: &aws_job_template
  account-url: AWS_ECR_ACCOUNT_URL
  aws-access-key-id: AWS_ACCESS_KEY_ID
  aws-secret-access-key: AWS_SECRET_ACCESS_KEY
  dockerfile: Dockerfile
  no-output-timeout: 20m
  workspace-root: '.'
  region: AWS_REGION
  repo: $AWS_RESOURCE_NAME_PREFIX
  create-repo: true
  path: '.'
  skip-when-tags-exist: false
  attach-workspace: true
  tag: $CIRCLE_WORKFLOW_ID

service_template: &service_template
  family: ${AWS_RESOURCE_NAME_PREFIX}-task
  cluster-name: ${AWS_RESOURCE_NAME_PREFIX}-cluster
  service-name: ${AWS_RESOURCE_NAME_PREFIX}-service
  container-image-name-updates: container=${AWS_RESOURCE_NAME_PREFIX},tag=${CIRCLE_WORKFLOW_ID}

orbs:
  node: circleci/node@4.4.0
  aws-ecr: circleci/aws-ecr@7.0.0
  aws-ecs: circleci/aws-ecs@2.2.1
  cypress: cypress-io/cypress@1.28.0
version: 2.1
workflows:
  staging_deploy:
    jobs:
      - test:
          name: unit test
          context: staging
          filters:
            branches:
              only: staging
      -  cypress/run:
          name: e2e test
          filters:
            branches:
              only: staging
          no-workspace: false
          record: true
          start: 'npm run start:mock:env'
          command: 'npm run cy:features'
      -  cypress/run:
          name: UI audit
          filters:
            branches:
              only: staging
          no-workspace: false
          record: true
          start: 'npm run start:mock:env'
          command: 'npm run cy:audit'
      - aws-ecr/build-and-push-image:
          context: staging
          filters:
            branches:
              only: staging
          requires:
            - unit test
            - e2e test
            - UI audit
          <<: *aws_job_template
      - aws-ecs/deploy-service-update:
          context: staging
          filters:
            branches:
              only: staging
          requires:
            - aws-ecr/build-and-push-image
          <<: *service_template

  uat_deploy:
    jobs:
      - test:
          name: unit test
          context: uat
          filters:
            branches:
              only: uat
      -  cypress/run:
          name: e2e test
          filters:
            branches:
              only: uat
          no-workspace: false
          record: true
          start: 'npm run start:mock:env'
          command: 'npm run cy:features'
      -  cypress/run:
          name: UI audit
          filters:
            branches:
              only: uat
          no-workspace: false
          record: true
          start: 'npm run start:mock:env'
          command: 'npm run cy:audit'
      - aws-ecr/build-and-push-image:
          context: uat
          filters:
            branches:
              only: uat
          requires:
            - unit test
            - e2e test
            - UI audit
          <<: *aws_job_template
      - aws-ecs/deploy-service-update:
          context: uat
          filters:
           branches:
             only: uat
          requires:
              - aws-ecr/build-and-push-image
          <<: *service_template

  production_deploy:
    jobs:
      - request-approval:
          type: approval
          filters:
            branches:
              only: master
          requires:
            - aws-ecr/build-and-push-image
      - test:
          name: unit test
          context: production
          filters:
            branches:
              only: master
      -  cypress/run:
          name: e2e test
          filters:
            branches:
              only: master
          no-workspace: false
          record: true
          start: 'npm run start:mock:env'
          command: 'npm run cy:features'
      -  cypress/run:
          name: UI audit
          filters:
            branches:
              only: master
          no-workspace: false
          record: true
          start: 'npm run start:mock:env'
          command: 'npm run cy:audit'
      - aws-ecr/build-and-push-image:
          context: production
          filters:
            branches:
              only: master
          requires:
            - unit test
            - e2e test
            - UI audit
          <<: *aws_job_template
      - aws-ecs/deploy-service-update:
            context: production
            filters:
                 branches:
                  only: master
            requires:
              - request-approval
            <<: *service_template
