jobs:
  test:
    executor:
      name: node/default
      tag: '14.15'
    steps:
      - checkout
      - node/install-packages
      - run:
          command: npx audit-ci -h -c
      - run:
          command: npm ci
      - run:
          command: npm run build
      - run:
          command: echo "$AWS_ECR_ACCOUNT_URL"
  deploy:
    steps:
      - run:
          command: chmod x+ deploy.sh
      - run:
          command: |
             if [ "${CIRCLE_BRANCH}" = "staging" ]; then
                echo "${AWS_ACCESS_KEY_ID}"
                ./deploy.sh
             fi
orbs:
  node: circleci/node@4.1.0
  aws-ecr: circleci/aws-ecr@6.2.0
  aws-ecs: circleci/aws-ecs@0.0.11
version: 2.1
workflows:
  run_tests:
    jobs:
      - test:
          filters:
            branches:
              only: staging
  deploy_aws:
    jobs:
      - deploy:
          filters:
             branches:
                 only: staging
          requires:
             - test
