// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'dark-mode': string;
  'light-mode': string;
}
export const cssExports: CssExports;
export default cssExports;
