FROM ubuntu

WORKDIR /

RUN apt-get update -y

RUN apt-get install -y nano wget curl dialog net-tools

RUN curl -sL https://deb.nodesource.com/setup_14.x |  bash -

RUN apt-get install -y nodejs

WORKDIR /app

COPY package*.json ./

RUN npm ci

COPY . .

CMD [ "npm", "run", "test:runner" ]

