// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  about: string;
  'bg-color': string;
  center: string;
  contact: string;
  h1: string;
  home: string;
  'image-container': string;
}
export const cssExports: CssExports;
export default cssExports;
