// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  circle1: string;
  circleBase: string;
  navigation: string;
  padding: string;
}
export const cssExports: CssExports;
export default cssExports;
