// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  switch_box: string;
  'theme-switch__input': string;
  'theme-switch__label': string;
}
export const cssExports: CssExports;
export default cssExports;
