// Generated by https://quicktype.io

export interface Pa11y {
  documentTitle: string;
  pageUrl: string;
  issues: Issue[];
}

export interface Issue {
  code: string;
  type: string;
  typeCode: number;
  message: string;
  context: string;
  selector: string;
  runner: string;
  runnerExtras: RunnerExtra[];
}

export interface RunnerExtra {
  description: string;
  impact: string;
  help: string;
  helpUrl: string;
}
