name: Cypress Tests

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v2

      - name: Install and build UI
        uses: cypress-io/github-action@v2
        with:
          runTests: false
          build: npm run build
          config-file: shared/config/cypress.json

      # - name: Save bundleAnalyzer folder
      #   uses: actions/upload-artifact@v2
      #   with:
      #     if-no-files-found: error
      #     path: bundleAnalyzer

  unit-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v2

      - name: Install
        uses: cypress-io/github-action@v2
        with:
          command: npm run test:coverage
          config-file: shared/config/cypress.json

      # - name: Save coverage folder
      #   uses: actions/upload-artifact@v2
      #   with:
      #     if-no-files-found: error
      #     path: coverage

  chrome:
    runs-on: ubuntu-latest
    name: E2E on Chrome

    steps:
      - uses: actions/checkout@v2
      - uses: cypress-io/github-action@v2
        with:
          start: npm start
          command: npm run cy:features
          browser: chrome
          headless: true
          config-file: shared/config/cypress.json

      # - name: Upload audit report
      # - uses: actions/upload-artifact@v1
      #   if: always()
      #   with:
      #     name: auditReport
      #     path: auditReport

  firefox:
    runs-on: ubuntu-latest
    container:
      image: cypress/browsers:node12.16.1-chrome80-ff73
      options: --user 1001

    name: E2E on Firefox
    steps:
      - uses: actions/checkout@v2
      - uses: cypress-io/github-action@v2
        with:
          start: npm start
          command: npm run cy:features
          browser: firefox
          headless: true
          config-file: shared/config/cypress.json

      # - name: Upload audit report
      # - uses: actions/upload-artifact@v1
      #   if: always()
      #   with:
      #     name: auditReport
      #     path: auditReport

  edge:
    runs-on: windows-latest
    name: E2E on Edge

    steps:
      - uses: actions/checkout@v2
      - uses: cypress-io/github-action@v2
        with:
          start-windows: npm run start:windows:server
          command: npm run cy:features
          browser: edge
          headless: true
          config-file: shared/config/cypress.json

      # - name: Upload audit report
      # - uses: actions/upload-artifact@v1
      #   if: always()
      #   with:
      #     name: auditReport
      #     path: auditReport

